# Refer https://github.com/zyrouge/web-status-monitor#configuration for documentation
entities:
    - url: "https://restreamer-09gx.onrender.com"
      method: "get"
    - url: "https://filestreambot-b5k6.onrender.com/"
      method: "get"
    - url: "https://restreamer-09gx.onrender.com/ui"
      method: "get"
