# Refer https://github.com/zyrouge/web-status-monitor#configuration for documentation
entities:
    - url: "https://talk-m6gd.onrender.com/umar"
      method: "get"
    - url: "https://talk-m6gd.onrender.com/9337"
      method: "get"
    - url: "https://talk-m6gd.onrender.com/umar920"
      method: "get"
